export const data = {
    lat: 41.161,
    lon: -81.071,
    timezone: "America/New_York",
    timezone_offset: -18000,
    current: {
        dt: 1677364068,
        sunrise: 1677326719,
        sunset: 1677366587,
        temp: 41.09,
        feels_like: 35.89,
        pressure: 1020,
        humidity: 51,
        dew_point: 25.23,
        uvi: 0.2,
        clouds: 0,
        visibility: 10000,
        wind_speed: 8.05,
        wind_deg: 320,
        weather: [
            {
                id: 800,
                main: "Clear",
                description: "clear sky",
                icon: "01d",
            },
        ],
    },
    hourly: [
        {
            dt: 1677362400,
            temp: 41.09,
            feels_like: 36.39,
            pressure: 1020,
            humidity: 51,
            dew_point: 25.23,
            uvi: 0.2,
            clouds: 0,
            visibility: 10000,
            wind_speed: 7.11,
            wind_deg: 318,
            wind_gust: 11.56,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677366000,
            temp: 39.16,
            feels_like: 34.83,
            pressure: 1020,
            humidity: 56,
            dew_point: 25.63,
            uvi: 0,
            clouds: 19,
            visibility: 10000,
            wind_speed: 5.91,
            wind_deg: 324,
            wind_gust: 7.81,
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677369600,
            temp: 35.87,
            feels_like: 32.31,
            pressure: 1020,
            humidity: 63,
            dew_point: 25.38,
            uvi: 0,
            clouds: 39,
            visibility: 10000,
            wind_speed: 4.25,
            wind_deg: 327,
            wind_gust: 4.29,
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677373200,
            temp: 32.54,
            feels_like: 32.54,
            pressure: 1021,
            humidity: 70,
            dew_point: 24.8,
            uvi: 0,
            clouds: 34,
            visibility: 10000,
            wind_speed: 2.15,
            wind_deg: 296,
            wind_gust: 2.46,
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677376800,
            temp: 29.5,
            feels_like: 29.5,
            pressure: 1021,
            humidity: 76,
            dew_point: 23.63,
            uvi: 0,
            clouds: 26,
            visibility: 10000,
            wind_speed: 1.99,
            wind_deg: 220,
            wind_gust: 1.99,
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677380400,
            temp: 26.94,
            feels_like: 21.79,
            pressure: 1020,
            humidity: 82,
            dew_point: 21.65,
            uvi: 0,
            clouds: 25,
            visibility: 10000,
            wind_speed: 4.38,
            wind_deg: 209,
            wind_gust: 4.52,
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677384000,
            temp: 27.3,
            feels_like: 20.66,
            pressure: 1019,
            humidity: 83,
            dew_point: 22.48,
            uvi: 0,
            clouds: 20,
            visibility: 10000,
            wind_speed: 5.97,
            wind_deg: 207,
            wind_gust: 10.98,
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677387600,
            temp: 27.59,
            feels_like: 20.8,
            pressure: 1019,
            humidity: 85,
            dew_point: 23.45,
            uvi: 0,
            clouds: 17,
            visibility: 10000,
            wind_speed: 6.22,
            wind_deg: 211,
            wind_gust: 16.37,
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677391200,
            temp: 27.91,
            feels_like: 20.71,
            pressure: 1018,
            humidity: 88,
            dew_point: 24.33,
            uvi: 0,
            clouds: 15,
            visibility: 10000,
            wind_speed: 6.8,
            wind_deg: 216,
            wind_gust: 21.88,
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677394800,
            temp: 28.49,
            feels_like: 20.98,
            pressure: 1017,
            humidity: 88,
            dew_point: 25.09,
            uvi: 0,
            clouds: 26,
            visibility: 10000,
            wind_speed: 7.4,
            wind_deg: 222,
            wind_gust: 25.84,
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677398400,
            temp: 29.43,
            feels_like: 21.42,
            pressure: 1017,
            humidity: 87,
            dew_point: 25.81,
            uvi: 0,
            clouds: 27,
            visibility: 10000,
            wind_speed: 8.46,
            wind_deg: 236,
            wind_gust: 29.53,
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677402000,
            temp: 30.06,
            feels_like: 21.78,
            pressure: 1016,
            humidity: 87,
            dew_point: 26.42,
            uvi: 0,
            clouds: 27,
            visibility: 10000,
            wind_speed: 9.17,
            wind_deg: 241,
            wind_gust: 30.89,
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677405600,
            temp: 30.51,
            feels_like: 21.83,
            pressure: 1016,
            humidity: 88,
            dew_point: 27.03,
            uvi: 0,
            clouds: 21,
            visibility: 10000,
            wind_speed: 10.09,
            wind_deg: 243,
            wind_gust: 31.63,
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677409200,
            temp: 30.4,
            feels_like: 21.76,
            pressure: 1016,
            humidity: 89,
            dew_point: 27.12,
            uvi: 0,
            clouds: 18,
            visibility: 10000,
            wind_speed: 9.98,
            wind_deg: 247,
            wind_gust: 31.47,
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677412800,
            temp: 30.22,
            feels_like: 21.2,
            pressure: 1015,
            humidity: 88,
            dew_point: 26.85,
            uvi: 0,
            clouds: 16,
            visibility: 10000,
            wind_speed: 10.63,
            wind_deg: 239,
            wind_gust: 31.54,
            weather: [
                {
                    id: 801,
                    main: "Clouds",
                    description: "few clouds",
                    icon: "02n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677416400,
            temp: 32.11,
            feels_like: 23.43,
            pressure: 1016,
            humidity: 82,
            dew_point: 26.85,
            uvi: 0.27,
            clouds: 6,
            visibility: 10000,
            wind_speed: 10.87,
            wind_deg: 247,
            wind_gust: 31.59,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677420000,
            temp: 36,
            feels_like: 27.66,
            pressure: 1016,
            humidity: 71,
            dew_point: 27.16,
            uvi: 0.85,
            clouds: 6,
            visibility: 10000,
            wind_speed: 12.37,
            wind_deg: 257,
            wind_gust: 29.51,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677423600,
            temp: 39.25,
            feels_like: 31.39,
            pressure: 1015,
            humidity: 59,
            dew_point: 25.88,
            uvi: 1.73,
            clouds: 6,
            visibility: 10000,
            wind_speed: 13.42,
            wind_deg: 268,
            wind_gust: 24.16,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677427200,
            temp: 42.12,
            feels_like: 35.01,
            pressure: 1015,
            humidity: 52,
            dew_point: 25.48,
            uvi: 2.7,
            clouds: 5,
            visibility: 10000,
            wind_speed: 13.49,
            wind_deg: 271,
            wind_gust: 21.77,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677430800,
            temp: 44.46,
            feels_like: 38.05,
            pressure: 1015,
            humidity: 47,
            dew_point: 25.27,
            uvi: 3.25,
            clouds: 4,
            visibility: 10000,
            wind_speed: 13.27,
            wind_deg: 274,
            wind_gust: 20.56,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677434400,
            temp: 46.15,
            feels_like: 40.19,
            pressure: 1014,
            humidity: 44,
            dew_point: 25.03,
            uvi: 3.21,
            clouds: 3,
            visibility: 10000,
            wind_speed: 13.29,
            wind_deg: 276,
            wind_gust: 20.47,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677438000,
            temp: 47.16,
            feels_like: 41.47,
            pressure: 1014,
            humidity: 42,
            dew_point: 24.85,
            uvi: 2.66,
            clouds: 0,
            visibility: 10000,
            wind_speed: 13.27,
            wind_deg: 278,
            wind_gust: 20.89,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677441600,
            temp: 47.39,
            feels_like: 41.9,
            pressure: 1013,
            humidity: 43,
            dew_point: 25.57,
            uvi: 1.7,
            clouds: 0,
            visibility: 10000,
            wind_speed: 12.77,
            wind_deg: 285,
            wind_gust: 20.78,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677445200,
            temp: 46.54,
            feels_like: 41.41,
            pressure: 1013,
            humidity: 48,
            dew_point: 27.41,
            uvi: 0.79,
            clouds: 0,
            visibility: 10000,
            wind_speed: 10.98,
            wind_deg: 290,
            wind_gust: 18.92,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677448800,
            temp: 43.93,
            feels_like: 39.09,
            pressure: 1014,
            humidity: 55,
            dew_point: 28.58,
            uvi: 0.22,
            clouds: 0,
            visibility: 10000,
            wind_speed: 8.63,
            wind_deg: 298,
            wind_gust: 16.46,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677452400,
            temp: 37.87,
            feels_like: 33.33,
            pressure: 1014,
            humidity: 68,
            dew_point: 28.06,
            uvi: 0,
            clouds: 0,
            visibility: 10000,
            wind_speed: 5.84,
            wind_deg: 306,
            wind_gust: 7.07,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677456000,
            temp: 34.84,
            feels_like: 30.38,
            pressure: 1015,
            humidity: 74,
            dew_point: 27.12,
            uvi: 0,
            clouds: 0,
            visibility: 10000,
            wind_speed: 5.03,
            wind_deg: 302,
            wind_gust: 5.06,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677459600,
            temp: 33.76,
            feels_like: 29.75,
            pressure: 1015,
            humidity: 76,
            dew_point: 26.8,
            uvi: 0,
            clouds: 0,
            visibility: 10000,
            wind_speed: 4.36,
            wind_deg: 293,
            wind_gust: 4.43,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677463200,
            temp: 33.15,
            feels_like: 29.34,
            pressure: 1015,
            humidity: 78,
            dew_point: 26.65,
            uvi: 0,
            clouds: 0,
            visibility: 10000,
            wind_speed: 4.07,
            wind_deg: 293,
            wind_gust: 4.16,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677466800,
            temp: 32.5,
            feels_like: 29.59,
            pressure: 1015,
            humidity: 79,
            dew_point: 26.33,
            uvi: 0,
            clouds: 0,
            visibility: 10000,
            wind_speed: 3.22,
            wind_deg: 303,
            wind_gust: 3.33,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677470400,
            temp: 31.68,
            feels_like: 31.68,
            pressure: 1015,
            humidity: 80,
            dew_point: 25.83,
            uvi: 0,
            clouds: 1,
            visibility: 10000,
            wind_speed: 2.53,
            wind_deg: 349,
            wind_gust: 2.59,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677474000,
            temp: 30.92,
            feels_like: 30.92,
            pressure: 1015,
            humidity: 81,
            dew_point: 25.38,
            uvi: 0,
            clouds: 1,
            visibility: 10000,
            wind_speed: 2.89,
            wind_deg: 45,
            wind_gust: 2.82,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677477600,
            temp: 30.31,
            feels_like: 26.65,
            pressure: 1015,
            humidity: 82,
            dew_point: 25.07,
            uvi: 0,
            clouds: 1,
            visibility: 10000,
            wind_speed: 3.56,
            wind_deg: 71,
            wind_gust: 3.44,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677481200,
            temp: 29.93,
            feels_like: 25.36,
            pressure: 1015,
            humidity: 82,
            dew_point: 24.89,
            uvi: 0,
            clouds: 34,
            visibility: 10000,
            wind_speed: 4.29,
            wind_deg: 86,
            wind_gust: 4.12,
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677484800,
            temp: 29.82,
            feels_like: 24.49,
            pressure: 1014,
            humidity: 83,
            dew_point: 24.82,
            uvi: 0,
            clouds: 27,
            visibility: 10000,
            wind_speed: 5.03,
            wind_deg: 96,
            wind_gust: 5.41,
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677488400,
            temp: 29.89,
            feels_like: 24.57,
            pressure: 1013,
            humidity: 82,
            dew_point: 24.84,
            uvi: 0,
            clouds: 40,
            visibility: 10000,
            wind_speed: 5.03,
            wind_deg: 97,
            wind_gust: 6.49,
            weather: [
                {
                    id: 802,
                    main: "Clouds",
                    description: "scattered clouds",
                    icon: "03n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677492000,
            temp: 30.52,
            feels_like: 24.64,
            pressure: 1012,
            humidity: 81,
            dew_point: 25.14,
            uvi: 0,
            clouds: 55,
            visibility: 10000,
            wind_speed: 5.79,
            wind_deg: 112,
            wind_gust: 10.89,
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677495600,
            temp: 30.65,
            feels_like: 24.46,
            pressure: 1012,
            humidity: 81,
            dew_point: 25.38,
            uvi: 0,
            clouds: 63,
            visibility: 10000,
            wind_speed: 6.22,
            wind_deg: 119,
            wind_gust: 12.57,
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677499200,
            temp: 31.59,
            feels_like: 24.66,
            pressure: 1010,
            humidity: 80,
            dew_point: 25.97,
            uvi: 0,
            clouds: 63,
            visibility: 10000,
            wind_speed: 7.49,
            wind_deg: 128,
            wind_gust: 20.24,
            weather: [
                {
                    id: 803,
                    main: "Clouds",
                    description: "broken clouds",
                    icon: "04n",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677502800,
            temp: 34.16,
            feels_like: 26.29,
            pressure: 1009,
            humidity: 76,
            dew_point: 27,
            uvi: 0.1,
            clouds: 100,
            visibility: 10000,
            wind_speed: 10.25,
            wind_deg: 118,
            wind_gust: 25.46,
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            pop: 0,
        },
        {
            dt: 1677506400,
            temp: 36.5,
            feels_like: 28.2,
            pressure: 1007,
            humidity: 72,
            dew_point: 28.15,
            uvi: 0.32,
            clouds: 100,
            visibility: 10000,
            wind_speed: 12.59,
            wind_deg: 131,
            wind_gust: 31.29,
            weather: [
                {
                    id: 804,
                    main: "Clouds",
                    description: "overcast clouds",
                    icon: "04d",
                },
            ],
            pop: 0.05,
        },
        {
            dt: 1677510000,
            temp: 37.76,
            feels_like: 29.44,
            pressure: 1005,
            humidity: 80,
            dew_point: 31.84,
            uvi: 0.63,
            clouds: 100,
            visibility: 5874,
            wind_speed: 13.56,
            wind_deg: 126,
            wind_gust: 34.54,
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            pop: 0.67,
            rain: {
                "1h": 0.84,
            },
        },
        {
            dt: 1677513600,
            temp: 37.94,
            feels_like: 29.32,
            pressure: 1002,
            humidity: 92,
            dew_point: 35.62,
            uvi: 0.19,
            clouds: 100,
            visibility: 5810,
            wind_speed: 14.61,
            wind_deg: 126,
            wind_gust: 37.56,
            weather: [
                {
                    id: 502,
                    main: "Rain",
                    description: "heavy intensity rain",
                    icon: "10d",
                },
            ],
            pop: 1,
            rain: {
                "1h": 4.25,
            },
        },
        {
            dt: 1677517200,
            temp: 39,
            feels_like: 30.45,
            pressure: 1000,
            humidity: 93,
            dew_point: 36.79,
            uvi: 0.23,
            clouds: 100,
            visibility: 10000,
            wind_speed: 15.37,
            wind_deg: 116,
            wind_gust: 38.39,
            weather: [
                {
                    id: 501,
                    main: "Rain",
                    description: "moderate rain",
                    icon: "10d",
                },
            ],
            pop: 1,
            rain: {
                "1h": 1.03,
            },
        },
        {
            dt: 1677520800,
            temp: 42.12,
            feels_like: 34.41,
            pressure: 996,
            humidity: 94,
            dew_point: 40.3,
            uvi: 0.22,
            clouds: 100,
            visibility: 6969,
            wind_speed: 15.48,
            wind_deg: 138,
            wind_gust: 40.06,
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            pop: 1,
            rain: {
                "1h": 0.63,
            },
        },
        {
            dt: 1677524400,
            temp: 42.8,
            feels_like: 35.1,
            pressure: 993,
            humidity: 96,
            dew_point: 41.31,
            uvi: 0.41,
            clouds: 100,
            visibility: 8237,
            wind_speed: 16.2,
            wind_deg: 126,
            wind_gust: 35.81,
            weather: [
                {
                    id: 501,
                    main: "Rain",
                    description: "moderate rain",
                    icon: "10d",
                },
            ],
            pop: 1,
            rain: {
                "1h": 2.52,
            },
        },
        {
            dt: 1677528000,
            temp: 42.75,
            feels_like: 40.33,
            pressure: 992,
            humidity: 98,
            dew_point: 41.81,
            uvi: 0.26,
            clouds: 100,
            visibility: 1716,
            wind_speed: 4.18,
            wind_deg: 160,
            wind_gust: 17.67,
            weather: [
                {
                    id: 502,
                    main: "Rain",
                    description: "heavy intensity rain",
                    icon: "10d",
                },
            ],
            pop: 1,
            rain: {
                "1h": 9.35,
            },
        },
        {
            dt: 1677531600,
            temp: 43.07,
            feels_like: 37.31,
            pressure: 991,
            humidity: 98,
            dew_point: 42.12,
            uvi: 0.12,
            clouds: 100,
            visibility: 10000,
            wind_speed: 10.36,
            wind_deg: 106,
            wind_gust: 18.37,
            weather: [
                {
                    id: 502,
                    main: "Rain",
                    description: "heavy intensity rain",
                    icon: "10d",
                },
            ],
            pop: 1,
            rain: {
                "1h": 5.54,
            },
        },
    ],
    daily: [
        {
            dt: 1677344400,
            sunrise: 1677326719,
            sunset: 1677366587,
            moonrise: 1677336900,
            moonset: 0,
            moon_phase: 0.2,
            temp: {
                day: 38.03,
                min: 22.21,
                max: 41.4,
                night: 27.3,
                eve: 39.16,
                morn: 24.28,
            },
            feels_like: {
                day: 34.56,
                night: 20.66,
                eve: 34.83,
                morn: 17.26,
            },
            pressure: 1023,
            humidity: 43,
            dew_point: 17.38,
            wind_speed: 8.5,
            wind_deg: 270,
            wind_gust: 12.12,
            weather: [
                {
                    id: 600,
                    main: "Snow",
                    description: "light snow",
                    icon: "13d",
                },
            ],
            clouds: 100,
            pop: 0.69,
            snow: 0.61,
            uvi: 2.95,
        },
        {
            dt: 1677430800,
            sunrise: 1677413029,
            sunset: 1677453058,
            moonrise: 1677425100,
            moonset: 1677390240,
            moon_phase: 0.23,
            temp: {
                day: 44.46,
                min: 27.59,
                max: 47.39,
                night: 31.68,
                eve: 37.87,
                morn: 30.4,
            },
            feels_like: {
                day: 38.05,
                night: 31.68,
                eve: 33.33,
                morn: 21.76,
            },
            pressure: 1015,
            humidity: 47,
            dew_point: 25.27,
            wind_speed: 13.49,
            wind_deg: 271,
            wind_gust: 31.63,
            weather: [
                {
                    id: 800,
                    main: "Clear",
                    description: "clear sky",
                    icon: "01d",
                },
            ],
            clouds: 4,
            pop: 0,
            uvi: 3.25,
        },
        {
            dt: 1677517200,
            sunrise: 1677499338,
            sunset: 1677539528,
            moonrise: 1677513660,
            moonset: 1677480660,
            moon_phase: 0.25,
            temp: {
                day: 39,
                min: 29.82,
                max: 53.38,
                night: 50.81,
                eve: 48.45,
                morn: 30.65,
            },
            feels_like: {
                day: 30.45,
                night: 49.91,
                eve: 44.37,
                morn: 24.46,
            },
            pressure: 1000,
            humidity: 93,
            dew_point: 36.79,
            wind_speed: 20.6,
            wind_deg: 242,
            wind_gust: 42.66,
            weather: [
                {
                    id: 502,
                    main: "Rain",
                    description: "heavy intensity rain",
                    icon: "10d",
                },
            ],
            clouds: 100,
            pop: 1,
            rain: 35.03,
            uvi: 0.63,
        },
        {
            dt: 1677603600,
            sunrise: 1677585646,
            sunset: 1677625998,
            moonrise: 1677602580,
            moonset: 1677570840,
            moon_phase: 0.29,
            temp: {
                day: 41.54,
                min: 34.27,
                max: 49.69,
                night: 34.27,
                eve: 39.88,
                morn: 41.09,
            },
            feels_like: {
                day: 33.21,
                night: 34.27,
                eve: 34.95,
                morn: 32.16,
            },
            pressure: 1009,
            humidity: 72,
            dew_point: 32.74,
            wind_speed: 21.72,
            wind_deg: 256,
            wind_gust: 41.99,
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: 98,
            pop: 0.99,
            rain: 0.26,
            uvi: 2.82,
        },
        {
            dt: 1677690000,
            sunrise: 1677671953,
            sunset: 1677712468,
            moonrise: 1677691920,
            moonset: 1677660660,
            moon_phase: 0.32,
            temp: {
                day: 56.35,
                min: 32.29,
                max: 61,
                night: 50.99,
                eve: 57.16,
                morn: 32.65,
            },
            feels_like: {
                day: 54.37,
                night: 49.73,
                eve: 56.07,
                morn: 24.89,
            },
            pressure: 1008,
            humidity: 57,
            dew_point: 41.36,
            wind_speed: 17.87,
            wind_deg: 212,
            wind_gust: 36.66,
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: 58,
            pop: 0.8,
            rain: 1.23,
            uvi: 3.63,
        },
        {
            dt: 1677776400,
            sunrise: 1677758260,
            sunset: 1677798937,
            moonrise: 1677781680,
            moonset: 1677750000,
            moon_phase: 0.35,
            temp: {
                day: 47.53,
                min: 33.78,
                max: 49.26,
                night: 35.62,
                eve: 37.36,
                morn: 35.87,
            },
            feels_like: {
                day: 46.87,
                night: 28.71,
                eve: 30.52,
                morn: 28.78,
            },
            pressure: 1012,
            humidity: 50,
            dew_point: 29.62,
            wind_speed: 10.18,
            wind_deg: 297,
            wind_gust: 23.2,
            weather: [
                {
                    id: 500,
                    main: "Rain",
                    description: "light rain",
                    icon: "10d",
                },
            ],
            clouds: 19,
            pop: 0.4,
            rain: 0.14,
            uvi: 4,
        },
        {
            dt: 1677862800,
            sunrise: 1677844565,
            sunset: 1677885406,
            moonrise: 1677871620,
            moonset: 1677838920,
            moon_phase: 0.38,
            temp: {
                day: 36.52,
                min: 27.03,
                max: 38.89,
                night: 27.03,
                eve: 27.79,
                morn: 38.89,
            },
            feels_like: {
                day: 26.91,
                night: 14.43,
                eve: 15.19,
                morn: 31.17,
            },
            pressure: 989,
            humidity: 96,
            dew_point: 35.17,
            wind_speed: 25.66,
            wind_deg: 18,
            wind_gust: 44.78,
            weather: [
                {
                    id: 616,
                    main: "Snow",
                    description: "rain and snow",
                    icon: "13d",
                },
            ],
            clouds: 100,
            pop: 1,
            rain: 28.73,
            snow: 29.22,
            uvi: 4,
        },
        {
            dt: 1677949200,
            sunrise: 1677930870,
            sunset: 1677971875,
            moonrise: 1677961800,
            moonset: 1677927360,
            moon_phase: 0.41,
            temp: {
                day: 26.06,
                min: 18.57,
                max: 26.8,
                night: 20.64,
                eve: 22.28,
                morn: 18.57,
            },
            feels_like: {
                day: 16.02,
                night: 12.9,
                eve: 13.46,
                morn: 5.97,
            },
            pressure: 1017,
            humidity: 77,
            dew_point: 19.49,
            wind_speed: 17.13,
            wind_deg: 342,
            wind_gust: 33.31,
            weather: [
                {
                    id: 602,
                    main: "Snow",
                    description: "heavy snow",
                    icon: "13d",
                },
            ],
            clouds: 90,
            pop: 1,
            snow: 8.71,
            uvi: 4,
        },
    ],
};
